language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - '8'
script:
  - npm run lint
  - npm run cy:run -- --record
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
